version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: database_container
    environment:
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  api:
    container_name: backend_container
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "5000:5000"
  client:
    container_name: frontend_container
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
